backend:
  replicas: 1
  image: icr.io/cr-vsanchez/imagen-proyecto-backend-production:1.1.0-SNAPSHOT
  containerPort: 8080
  resources:
    requests:
      memory: "256Mi"
      cpu: "500m"
    limits:
      memory: "512Mi"
      cpu: "1000m"
  env:
    SPRING_DB_HOST: "10.251.10.34"
    SPRING_DB_PORT: "5432"
    SPRING_DB_NAME: "orquestas"
    SPRING_DB_USER: "vsanchez"
    SPRING_DB_PASSWORD: "mypassword"
  service:
    port: 8080
    type: ClusterIP

