backend:
  name: backend  # Nombre del backend
  replicas: 1  # Número de réplicas
  namespace: ""
  image:
    repository: icr.io/cr-vsanchez/imagen-proyecto-backend-develop
    tag: "0.0.1-SNAPSHOT"
  port: 8080  # Puerto de la aplicación
  SPRING_DB_HOST: "10.251.10.34"
  SPRING_DB_PORT: "5432"
  SPRING_DB_NAME: "orquestas"
  SPRING_DB_USER: "vsanchez"
  SPRING_DB_PASSWORD: "mypassword"
  resources:
    requests:
      memory: "128Mi"
      cpu: "250m"
    limits:
      memory: "256Mi"
      cpu: "500m"
  readinessProbe:
    initialDelaySeconds: 50
    periodSeconds: 10
  livenessProbe:
    initialDelaySeconds: 40
    periodSeconds: 10
  service:
    port: 80
    targetPort: 8080
    type: ClusterIP