name: Subir Chart
on:
  workflow_dispatch:
    inputs:
      MICROSERVICE:
        description: 'Nombre del microservicio'
        required: true
        default: 'backend'
jobs:
  subirCharts:
    uses: stemdo-labs/iac-ibmcloud-vsanchez/.github/workflows/SubirCharts.yaml@main
    secrets:
      TOKEN_GITHUB: "${{ secrets.TOKEN_GITHUB }}"
      HARBOR_PASSWORD: "${{ secrets.HARBOR_PASSWORD }}"
      ARM_CLIENT_ID: "${{ secrets.ARM_CLIENT_ID }}"
      ARM_CLIENT_SECRET: "${{ secrets.ARM_CLIENT_SECRET }}"
      ARM_TENANT_ID: "${{ secrets.ARM_TENANT_ID }}"
      ARM_SUBSCRIPTION_ID: "${{ secrets.ARM_SUBSCRIPTION_ID }}"
      APIKEY: "${{ secrets.APIKEY }}"
    with:
      MICROSERVICE: "${{ inputs.MICROSERVICE }}"

